### ISSUE TITLE
is it possible to delete lines?

### ISSUE THREAD

**Issue by justrajdeep** [stefandtw/quickfix-reflector.vim#20]
Hi 

Great plugin!!!

This might be an enhancement request, but is it possible to delete lines?

I am not asking about deleting lines **in** the quick-fix window, I am asking for deleting lines **from** the quickfix window in the respective files.

It would be great if you can support this. Thanks in advance

**Comment by stefandtw** [comment]
There are two problems:

- There is no intuitive way a user can indicate that a line should be deleted. They would need to call a special command on relevant lines, or replace the text with a special keyword, like "DEL". This is probably not a problem for someone who relly needs that functionality, but I still prefer to keep things simple and intuitive.
- Creating and deleting lines would make the plugin code more complex in general.

That's why I don't really want to add that behaviour.

Perhaps you could create a macro that deletes the current line. It would start by pressing `<CR>` to jump to your file, then `dd` to delete, maybe `:w` to save, and `:copen` to jump back to the quickfix window. After you recorded the macro, paste it into your .vimrc and map it to a key like this:

    nnoremap <C-d> <CR>dd:w<CR>:copen<CR>

Voila, you got your own key (Control-d) to delete a line from the quickfix window. (Actually I got `^M` instead of `<CR>`. They both seem to work, but pasting `^M` here converts it into line-breaks)

**Comment by justrajdeep** [comment]
Thanks :)
